name: CI Pull Request Open
on:
  pull_request:
jobs:
  image:
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: "-Xmx1500m -XX:+HeapDumpOnOutOfMemoryError"
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.6
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: oracle
          cache: maven
      - run: mvn --version
      - name: Build with Maven
        run: mvn clean install -B -e -DskipTests
      - name: Test with Maven
        run: |
          mvn verify -B -e -Dsurefire.rerunFailingTestsCount=2 -Dmaven.test.failure.ignore=true -Dansi.strip=true -Pnative
      - name: Publish Test Report
        if: success() || failure()
        uses: ScaCap/action-surefire-report@v1
      - name: Publish Flaky Tests
        uses: ./.github/actions/upload-flaky-tests
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          job-name: Base IT
